### ISSUE TITLE
群晖反代配置下，通过 HTTPS 访问 KasmVNC 时出现 lastActiveAt 的 JavaScript 错误

### ISSUE THREAD

**Issue by mapleshadow** [YuCat-OVO/BaiduNetdisk-Docker#12]
![image](https://github.com/user-attachments/assets/a7f1f108-9fe1-4a0f-ad04-e560b4fb9717)
如图

**Comment by mapleshadow** [comment]
换成8080端口的http就好了，哥们，https的有问题啊

**Comment by mapleshadow** [comment]
不对，我说错了，应该是不能做反代理，一旦反代理就报这个错误

**Comment by YuCat-OVO** [comment]
@mapleshadow 您好，我更新了 README 添加了 Nginx 的反代示例，您可以尝试更改配置使用看看。或者前往[文档](https://kasmweb.com/docs/latest/how_to/reverse_proxy.html)查看其它平台的示例。

**Comment by mapleshadow** [comment]
我是群晖，简而言之，用https协议访问就报这个错

**Comment by YuCat-OVO** [comment]
感谢您的反馈，由于我无法在现有信息的基础上复现或进一步排查问题，将暂时关闭此 Issue。如果您后续有更多的详细信息或可复现的步骤，欢迎随时重新打开或提交新 Issue！感谢您的理解与支持！
